version: 2.1

jobs:
  build-flutter-linux-arm:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get update
            sudo apt-get install -y \
              curl unzip xz-utils git clang cmake ninja-build pkg-config libgtk-3-dev

      - run:
          name: Install Flutter SDK
          command: |
            FLUTTER_VERSION=3.13.9
            CHANNEL=stable
            BASEURL="https://storage.googleapis.com/flutter_infra_release/releases/$CHANNEL/linux/flutter_linux_$FLUTTER_VERSION-$CHANNEL.tar.xz"
            curl -o flutter.tar.xz $BASEURL
            tar xf flutter.tar.xz
            echo 'export PATH="$PWD/flutter/bin:$PATH"' >> $BASH_ENV

      - run:
          name: Replace x64 Dart SDK with ARM64 Dart SDK
          command: |
            DART_VERSION=3.1.5
            curl -o dart-sdk.zip https://storage.googleapis.com/dart-archive/channels/stable/release/$DART_VERSION/sdk/dartsdk-linux-arm64-release.zip
            unzip -o dart-sdk.zip
            rm -rf flutter/bin/cache/dart-sdk
            mv dart-sdk flutter/bin/cache/dart-sdk

      - run:
          name: Clean stale build and Dart artifacts
          command: |
            rm -rf flutter/bin/cache
            rm -rf .dart_tool build linux

      - run:
          name: Enable Linux desktop support
          command: |
            source $BASH_ENV
            flutter config --enable-linux-desktop

      - run:
          name: Run flutter doctor
          command: |
            source $BASH_ENV
            flutter doctor

      - run:
          name: Get Dart/Flutter dependencies
          command: |
            source $BASH_ENV
            flutter pub get

      - run:
          name: Optional flutter clean
          command: |
            source $BASH_ENV
            flutter clean

      - run:
          name: Build Linux ARM64 ELF
          command: |
            source $BASH_ENV
            flutter create .
            flutter build linux
      - run:
          name: Zip Linux ARM64 build output
          command: |
            cd build/linux/arm64/release/
            zip -r flutter_linux_arm64.zip bundle
      - store_artifacts:
          path: build/linux/arm64/release/flutter_linux_arm64.zip
          destination: flutter_linux_arm64.zip

workflows:
  build:
    jobs:
      - build-flutter-linux-arm
